### PR TITLE
Improve Results Plotting

### LINKED ISSUE #103: GraphViz Dependency Not Covered
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

The GraphViz software is not autmatically installed in the environment.yaml, and would need either executable for windows or `brew install graphviz` on mac to install properly. 

I hot fixed the code in 9bbc9f6a8b445264fae32da932f45241e54ebee8

https://github.com/PyPSA/pypsa-usa/blob/8cc3e5b2137ea4cf06bb08ea0e64a7d63e71312b/workflow/Snakefile#L620-L630

Fixed with this commented out in snakefile:
https://github.com/PyPSA/pypsa-usa/blob/8cc3e5b2137ea4cf06bb08ea0e64a7d63e71312b/workflow/Snakefile#L74-L75

We could probably have a config for produce_dag so that developers can automatically have dags be produced.

### Steps To Reproduce

_No response_

### Expected Behavior

_No response_

### Error Message

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ktehranchi**
Closes #103, #93 

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Changed dependencies are added to `envs/environment.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv`.

### CODE REVIEW

**Comment by trevorb1** [comment]
@ktehranchi I did quite a big refactor of the visualization module and have added plots for the items identified in issue ticket #93! Did you mind giving it a quick run on your side (just `plot_results.py`) to see if you can think of any remaining charts to add, please? 

Also, in the issue ticket there is an item for `Output tables and charts of all capex, marginal cost, opex for each plant , plant type`. I think this is important to add, but should be moved to its own issue ticket, as its not really viz related. If you agree, I will create that. There are a few functions added in this PR that can be utilized for making these summary tables. 

Thanks!

**Comment by ktehranchi** [comment]
@trevorb1 
A couple bugs remain:
- if load shedding is set to true in an operations model there will be an error thrown
```
    plot_base_capacity(n, onshore_regions, snakemake.output["capacity_map_base"], **snakemake.wildcards)
  File "/Users/kamrantehranchi/Local_Documents/pypsa-usa/workflow/.snakemake/scripts/tmprgndvdmo.plot_figures.py", line 629, in plot_base_capacity
    fig, _ = plot_capacity_map(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/kamrantehranchi/Local_Documents/pypsa-usa/workflow/.snakemake/scripts/tmprgndvdmo.plot_figures.py", line 560, in plot_capacity_map
    n.plot(
  File "/Users/kamrantehranchi/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pypsa/plot.py", line 252, in plot
    assert bus_sizes.index.levels[1].isin(bus_colors.index).all(), (
AssertionError: Colors not defined for all elements in the second MultiIndex level of bus_sizes, please make sure that all the elements are included in bus_colors or in n.carriers.color
```

- Currently with config options set to the default but switch load shedding off , and operations off I get this error as well for battery dispatch: 
```
  File "/Users/kamrantehranchi/Local_Documents/pypsa-usa/workflow/.snakemake/scripts/tmphsdehihn.plot_figures.py", line 814, in <module>
    plot_production_area(n, snakemake.output["production_area"], **snakemake.wildcards)
  File "/Users/kamrantehranchi/Local_Documents/pypsa-usa/workflow/.snakemake/scripts/tmphsdehihn.plot_figures.py", line 453, in plot_production_area
    energy_mix[snapshots].plot.area(ax=ax, alpha=0.7, legend="reverse", color=color_palette)
  File "/Users/kamrantehranchi/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/plotting/_core.py", line 1534, in area
    return self(kind="area", x=x, y=y, stacked=stacked, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamrantehranchi/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/plotting/_core.py", line 975, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamrantehranchi/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/plotting/_matplotlib/__init__.py", line 71, in plot
    plot_obj.generate()
  File "/Users/kamrantehranchi/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/plotting/_matplotlib/core.py", line 448, in generate
    self._make_plot()
  File "/Users/kamrantehranchi/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/plotting/_matplotlib/core.py", line 1384, in _make_plot
    newlines = plotf(
               ^^^^^^
  File "/Users/kamrantehranchi/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/plotting/_matplotlib/core.py", line 1432, in _ts_plot
    lines = self._plot(ax, data.index, data.values, style=style, **kwds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamrantehranchi/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/plotting/_matplotlib/core.py", line 1558, in _plot
    y_values = cls._get_stacked_values(ax, stacking_id, y, kwds["label"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamrantehranchi/miniforge3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/plotting/_matplotlib/core.py", line 1467, in _get_stacked_values
    raise ValueError(
ValueError: When stacked is True, each column must be either all positive or all negative. Column 'battery' contains both positive and negative values
```

I can take a look at this in the morning, in the past I set two variables one for discharge and one for charging and plotted them separately.

**Comment by trevorb1** [comment]
@trevorb1 todo: 

- [ ] Remove `matplotlibrc`
- [ ] Change location of plotting config

**Comment by ktehranchi** [comment]
@trevorb1 I think I found the issue with the OGCT dispatching before CCGT. In the network.generators_t.marginal_cost timeseries of marginal costs, only the OGCT were assigned marginal costs, most of which are way lower than the single hourly marginal costs of the CCGT assigned.

I'll take a look tomorrow at how these time-series MC values were assigned.

Plot of single hourly marginal costs from `network.generators`:  
Screen Shot 2023-11-08 at 9 28 42 PM

Plot of OCGT monthly average of marginal cost:
Screen Shot 2023-11-08 at 9 31 11 PM

**Comment by trevorb1** [comment]
@ktehranchi I think the plotting colour error being raised can be traced back to the `add_load_shedding` function in the operation model. Seems like there may be a bug in this function from PyPSA. I think the generator carrier is being added as `load`, but the network carrier is being added as `Load`. The capitalization of `L` is throwing the error when searching for the colour code. I will double check this is the issue tomorrow, then probably start an issue on the PyPSA repo to get their opinion.

https://github.com/PyPSA/PyPSA/blob/9df3c7e951438375e0a4e7f4f52fd95cc3daaa7c/pypsa/optimization/optimize.py#L679-L722

 In the mean time, I have hotfixed this in the last commit. Since you have experience implementing load shedding, would you mind having a super quick look just to make sure my solution makes sense please :)

**Comment by trevorb1** [comment]
Ahhh. Nice catch on the marginal costs! It was writing over the existing marginal costs when introducing a new technologies marginal cost timeseries. I think my last commit fixed it! 

image

**Comment by trevorb1** [comment]
@ktehranchi On the area plots right now, the charts show batteries charging and discharging as positive and negative respectively. This works okay and is shown below as as example (I know the values are very small, but it shows the point haha) 

image

The other option is to show all values as positive, so during some time slices the system will graphically produce more then demand. I tend to prefer this option, but just wanted to get your thoughts! If you like how it's currently implemented now, thats no worries at all though :)

**Comment by ktehranchi** [comment]
> Ahhh. Nice catch on the marginal costs! It was writing over the existing marginal costs when introducing a new technologies marginal cost timeseries. I think my last commit fixed it! @ktehranchi Do you have a resource on approximate marginal cost values for CCGT and OCGT generators in WECC we can just spot check against? If not, I can take a look!
> 
> image

Nice, thanks for fixing! The values in the first histogram are from WECC data that we ingest.

**Comment by ktehranchi** [comment]
> @ktehranchi I think the plotting colour error being raised can be traced back to the `add_load_shedding` function in the operation model. Seems like there may be a bug in this function from PyPSA. I think the generator carrier is being added as `load`, but the network carrier is being added as `Load`. The capitalization of `L` is throwing the error when searching for the colour code. I will double check this is the issue tomorrow, then probably start an issue on the PyPSA repo to get their opinion.
> 
> https://github.com/PyPSA/PyPSA/blob/9df3c7e951438375e0a4e7f4f52fd95cc3daaa7c/pypsa/optimization/optimize.py#L679-L722
> 
> In the mean time, I have hotfixed this in the last commit. Since you have experience implementing load shedding, would you mind having a super quick look just to make sure my solution makes sense 

nice find! Hot fix looks good.

**Comment by ktehranchi** [comment]
> @ktehranchi On the area plots right now, the charts show batteries charging and discharging as positive and negative respectively. This works okay and is shown below as as example (I know the values are very small, but it shows the point haha)
> 
> image
> 
> The other option is to show all values as positive, so during some time slices the system will graphically produce more then demand. I tend to prefer this option, but just wanted to get your thoughts! If you like how it's currently implemented now, thats no worries at all though :)

Okay good to know the plotting is working. I'll investigate what's going on with dispatch.... In regards to above the line/below the line, I don't have a preference so which ever you like is good with me! I think a different default color would be cool tho >.<

**Comment by ktehranchi** [comment]
@trevorb1 I think we should merge this. I have some changes in my OSW branch that has battery dispatching correctly, and will merge that in after

**Comment by trevorb1** [comment]
> > Ahhh. Nice catch on the marginal costs! It was writing over the existing marginal costs when introducing a new technologies marginal cost timeseries. I think my last commit fixed it! @ktehranchi Do you have a resource on approximate marginal cost values for CCGT and OCGT generators in WECC we can just spot check against? If not, I can take a look!
> 
> Nice, thanks for fixing! The values in the first histogram are from WECC data that we ingest.

Hmm... I guess our marginal cost values are a little bit lower then what WECC is suggesting? But in any case, I agree with getting this merged in then that can be a different issue. Thanks!

**Pull request merged**
