### PR TITLE
Removes PyPSA-Eur as a Submodule

### PR DESCRIPTION
**Pull request by ktehranchi**
## Changes proposed in this Pull Request

- Remove PyPSA-EUR as a submodule in the workflow (copy_config, prepare_network)

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [ ] Changed dependencies are added to `envs/environment.yaml`.
- [ ] Changes in configuration options are added in all of `config.default.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv`.

### CODE REVIEW

**Comment by trevorb1** [comment]
lgtm! It ran fine on my machine. You may want to delete the actual `workflow/scripts/subworkflows/pypsa-eur` folder as well? (I did my test run with it deleted)

**Review by trevorb1 — APPROVED** [review]

**Comment by trevorb1** [comment]
oh, actually. I get this warning while building the docs? But we can sort that out afterwards as well, as im not sure it was actually caused by this PR? 

```bash 
WARNING: autodoc: failed to import module 'retrieve_eia_data'; the following exception was raised:
No module named 'retrieve_eia_data'
```

**Comment by ktehranchi** [comment]
Opps okay I just merged

**Comment by ktehranchi** [comment]
> oh, actually. I get this warning while building the docs? But we can sort that out afterwards as well, as im not sure it was actually caused by this PR?
> 
> ```shell
> WARNING: autodoc: failed to import module 'retrieve_eia_data'; the following exception was raised:
> No module named 'retrieve_eia_data'
> ```

I fixed this in the docs... looks like an old error from when we switched completely too gridemissions. Will PR with my docs update

**Pull request merged**
