### PR TITLE
New plot, battery fix, config clean up.

### PR DESCRIPTION
**Pull request by ktehranchi**
## Changes proposed in this Pull Request
- [x] Adds brownfield map plot
- [x] constrains p_nom_min of batteries to p_nom
- [x] cleans up `config.default.yaml`
- [x] assigns haversine lengths to lines. (More work in-comming soon on TX capital costs)
- [x] Fixes monthly marginal cost data scaling issue

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Changed dependencies are added to `envs/environment.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`.
- [ ] Changes in configuration options are also documented in `doc/configtables/*.csv`.

### CODE REVIEW

**Comment by ktehranchi** [comment]
@trevorb1 

Constraining the p_nom_min for batteries to p_nom was the fix for batt dispatch. Issue now is that nuclear isn't being dispatched.... need to investigate... I think its the same marginal cost issue we had with CCGT and OCGT

**Comment by ktehranchi** [comment]
Update: found an issue here- I changed the multiply to divide.... This explains the low cost.
We want: $/MCF * (1 MCF / 1.036 MMBTU) * (1 MMBTU / 0.293 MWh) = $/MWh

https://github.com/PyPSA/pypsa-usa/blob/134d2511bbdf1680002cd12a5c58c166142c93b5/workflow/scripts/add_electricity.py#L335-L338

**Comment by trevorb1** [comment]
Nice catch!

**Comment by trevorb1** [comment]
On the point of nuclear dispatch, I will also look at issue #63 today which finishes the mapping of costs from the ATB.

**Pull request merged**
