### PR TITLE
Fixes bug in reading efs data

### LINKED ISSUE #184: Error in `add_electricity`
### Checklist

- [X] I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
- [X] I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`

### The Issue

Running the workflow on `master` branch throws an error for `add_electricity`

I am running the default config file, excetp changing snapshots to 

```yaml
snapshots:
  start: "2019-01-01"
  end: "2019-01-07"
  inclusive: "left"
```

### Steps To Reproduce

1. clone the repo
2. change snapshots to shown above 
3. run workflow 

### Expected Behavior

The workflow should run 

### Error Message

```shell
[Sat Feb 24 14:18:53 2024]
rule add_electricity:
    input: resources/western/profile_onwind.nc, resources/western/profile_offwind.nc, resources/western/profile_offwind_floating.nc, resources/western/profile_solar.nc, repo_data/locational_multipliers/biomass-retrofit-300mw.csv, repo_data/locational_multipliers/natural-gas-100mw.csv, repo_data/locational_multipliers/spv-tracking-150mw.csv, repo_data/locational_multipliers/fuel-cell-10mw.csv, repo_data/locational_multipliers/geothermal-50mw.csv, repo_data/locational_multipliers/biomass-50mw.csv, repo_data/locational_multipliers/natural-gas-1100mw.csv, repo_data/locational_multipliers/nuclear-1117mw.csv, repo_data/locational_multipliers/coal-ultra-supercritical.csv, repo_data/locational_multipliers/offshore-wind-40x10mw.csv, repo_data/locational_multipliers/csp-100mw.csv, repo_data/locational_multipliers/natural-gas-430mw-90ccs.csv, repo_data/locational_multipliers/battery-storage-4hr-50mw.csv, repo_data/locational_multipliers/natural-gas-retrofit-1100mw.csv, repo_data/locational_multipliers/battery-storage-2hr-50mw.csv, repo_data/locational_multipliers/spv-150mw.csv, repo_data/locational_multipliers/natural-gas-240mw.csv, repo_data/locational_multipliers/hydro-100mw.csv, repo_data/locational_multipliers/smr-600mw.csv, repo_data/locational_multipliers/onshore-wind-50mw.csv, repo_data/locational_multipliers/natural-gas-430mw.csv, repo_data/locational_multipliers/coal-ultra-supercritical-30ccs.csv, repo_data/locational_multipliers/onshore-wind-200mw.csv, repo_data/locational_multipliers/coal-ultra-supercritical-90ccs.csv, repo_data/locational_multipliers/natural-gas-20mw.csv, resources/western/elec_base_network.nc, resources/costs_2030.csv, resources/western/regions_onshore.geojson, repo_data/eia_plants_wecc.csv, repo_data/ads_plants_locs.csv, repo_data/eia_mappings/fuelCost22.csv, data/breakthrough_network/base_grid/plant.csv, data/breakthrough_network/base_grid/hydro.csv, data/breakthrough_network/base_grid/wind.csv, data/breakthrough_network/base_grid/solar.csv, data/breakthrough_network/base_grid/western/bus2sub.csv, data/GridEmissions/EIA_DMD_2018_2024.csv, data/nrel_efs/EFSLoadProfile_Reference_Moderate.csv, data/costs/ng_electric_power_price.csv
    output: resources/western/elec_base_network_l_pp.nc
    log: logs/western/add_electricity.log
    jobid: 11
    benchmark: benchmarks/western/add_electricity
    reason: Missing output files: resources/western/elec_base_network_l_pp.nc; Input files updated by another job: resources/western/profile_offwind_floating.nc, resources/western/regions_onshore.geojson, data/breakthrough_network/base_grid/western/bus2sub.csv, resources/western/elec_base_network.nc, resources/western/profile_onwind.nc, resources/western/profile_offwind.nc, resources/western/profile_solar.nc, resources/costs_2030.csv
    wildcards: interconnect=western
    resources: tmpdir=/tmp, mem_mb=18000, mem_mib=17167

INFO:pypsa.io:Imported network elec_base_network.nc has buses, lines, line_types, links, transformers
/home/trevor/repos/pypsa-usa/workflow/.snakemake/scripts/tmpb9u85az1.add_electricity.py:1203: DtypeWarning:

Columns (21,22,23,48,51,52,54,55,56,57) have mixed types. Specify dtype option on import or set low_memory=False.

INFO:__main__:Building Load Data using EFS demand
Traceback (most recent call last):
  File "/home/trevor/repos/pypsa-usa/workflow/.snakemake/scripts/tmpb9u85az1.add_electricity.py", line 1659, in <module>
    main(snakemake)
  File "/home/trevor/repos/pypsa-usa/workflow/.snakemake/scripts/tmpb9u85az1.add_electricity.py", line 1538, in main
    attach_demand(n, configuration)
  File "/home/trevor/repos/pypsa-usa/workflow/.snakemake/scripts/tmpb9u85az1.add_electricity.py", line 935, in attach_demand
    demand_per_bus = prepare_efs_demand(
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/trevor/repos/pypsa-usa/workflow/.snakemake/scripts/tmpb9u85az1.add_electricity.py", line 883, in prepare_efs_demand
    demand.index = n.snapshots
    ^^^^^^^^^^^^
  File "/home/trevor/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/trevor/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/trevor/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/trevor/miniconda3/envs/pypsa-usa/lib/python3.11/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 8758 elements, new values have 142 elements
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by trevorb1**
Closes #184

## Changes proposed in this Pull Request

In this PR I have updated the snapshot filtering for reading in efs data

## Checklist

- [x] I tested my contribution locally and it seems to work fine.
- [x] Code and workflow changes are sufficiently documented.
- [x] Changed dependencies are added to `envs/environment.yaml`.
- [x] Changes in configuration options are added in all of `config.default.yaml`.
- [x] Changes in configuration options are also documented in `doc/configtables/*.csv`.

### CODE REVIEW

**Comment by trevorb1** [comment]
Still need to address the following warnings when writing capacity factors 

```bash 
WARNING:pypsa.io:Snapshots DatetimeIndex(['2019-01-07 00:00:00', '2019-01-07 01:00:00',
               '2019-01-07 02:00:00', '2019-01-07 03:00:00',
               '2019-01-07 04:00:00', '2019-01-07 05:00:00'],
              dtype='datetime64[ns]', name='snapshot', freq=None) are missing from p_max_pu of Generator. Filling with default value '1.0'
INFO:__main__:Added connection cost of 55-113 USD/MW/a to offwind
INFO:__main__:Adding offwind capacity-factor profiles to the network.
WARNING:pypsa.io:Snapshots DatetimeIndex(['2019-01-07 00:00:00', '2019-01-07 01:00:00',
               '2019-01-07 02:00:00', '2019-01-07 03:00:00',
               '2019-01-07 04:00:00', '2019-01-07 05:00:00'],
              dtype='datetime64[ns]', name='snapshot', freq=None) are missing from p_max_pu of Generator. Filling with default value '1.0'
INFO:__main__:Adding onwind capacity-factor profiles to the network.
WARNING:pypsa.io:Snapshots DatetimeIndex(['2019-01-07 00:00:00', '2019-01-07 01:00:00',
               '2019-01-07 02:00:00', '2019-01-07 03:00:00',
               '2019-01-07 04:00:00', '2019-01-07 05:00:00'],
              dtype='datetime64[ns]', name='snapshot', freq=None) are missing from p_max_pu of Generator. Filling with default value '1.0'
INFO:__main__:Adding solar capacity-factor profiles to the network.
WARNING:pypsa.io:Snapshots DatetimeIndex(['2019-01-07 00:00:00', '2019-01-07 01:00:00',
               '2019-01-07 02:00:00', '2019-01-07 03:00:00',
               '2019-01-07 04:00:00', '2019-01-07 05:00:00'],
              dtype='datetime64[ns]', name='snapshot', freq=None) are missing from p_max_pu of Generator. Filling with default value '1.0'
```

**Comment by trevorb1** [comment]
@ktehranchi I believe this takes care of the `add_electricity` issue and warnings described above, but can you please confirm? :) 

Also, not sure why suddenly the the datetimes in `build_renewable_profiles` were failing. But if the solution I propose works, we should wrap this into a utility function, as `add_electricity` is implemented in the same way

**Review by ktehranchi — COMMENTED** [review]
Looks good- thanks for fixing this. The change in build renewable profiles has to do with the timezone shift from the EFS demand data.... not sure why we didn't get that error with the EIA data previously.

**Comment by ktehranchi** [comment]
This caused an issue where build_renewable_profiles now cannot build capacity factor profiles for the portion of the year not in 2019. I'm going to push a change to revert that file back to how it was until a proper solution is put together.

**Comment by trevorb1** [comment]
To clarify, the workflow still runs based on whatever time intervals you give, but these warnings are just printed out now? If true, we should put this in a new issue ticket and move discussion there? 

```bash 
WARNING:pypsa.io:Snapshots DatetimeIndex(['2019-01-07 00:00:00', '2019-01-07 01:00:00',
               '2019-01-07 02:00:00', '2019-01-07 03:00:00',
               '2019-01-07 04:00:00', '2019-01-07 05:00:00'],
              dtype='datetime64[ns]', name='snapshot', freq=None) are missing from p_max_pu of Generator. Filling with default value '1.0'
INFO:__main__:Added connection cost of 55-113 USD/MW/a to offwind
INFO:__main__:Adding offwind capacity-factor profiles to the network.
WARNING:pypsa.io:Snapshots DatetimeIndex(['2019-01-07 00:00:00', '2019-01-07 01:00:00',
               '2019-01-07 02:00:00', '2019-01-07 03:00:00',
               '2019-01-07 04:00:00', '2019-01-07 05:00:00'],
              dtype='datetime64[ns]', name='snapshot', freq=None) are missing from p_max_pu of Generator. Filling with default value '1.0'
INFO:__main__:Adding onwind capacity-factor profiles to the network.
WARNING:pypsa.io:Snapshots DatetimeIndex(['2019-01-07 00:00:00', '2019-01-07 01:00:00',
               '2019-01-07 02:00:00', '2019-01-07 03:00:00',
               '2019-01-07 04:00:00', '2019-01-07 05:00:00'],
              dtype='datetime64[ns]', name='snapshot', freq=None) are missing from p_max_pu of Generator. Filling with default value '1.0'
INFO:__main__:Adding solar capacity-factor profiles to the network.
WARNING:pypsa.io:Snapshots DatetimeIndex(['2019-01-07 00:00:00', '2019-01-07 01:00:00',
               '2019-01-07 02:00:00', '2019-01-07 03:00:00',
               '2019-01-07 04:00:00', '2019-01-07 05:00:00'],
              dtype='datetime64[ns]', name='snapshot', freq=None) are missing from p_max_pu of Generator. Filling with default value '1.0'
```

**Pull request merged**
